services:
  postgres:
    image: postgres:16.8-alpine3.21
    restart: always
    container_name: todo-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin01

  adminer:
      image: adminer
      container_name: admin-db
      restart: always
      ports:
        - 8080:8080