spring:
  datasource:
    url: jdbc:h2:mem:tododb
    driverClassName: org.h2.Driver
    username: "andreas"
    password: ""
  h2:
    console:
      enabled: true
      path: "/db-admin"
  profiles:
    active: "local"
  application:
    name: "todo-app-api"

server:
  port: 8090

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: "/"

