spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todos
    username: postgres
    password: admin01
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: todo-app-api

server:
  port: 9394

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /

